### ISSUE TITLE
ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by lpanebr** [jeroendoggen/youtube-to-mpd#12]
Everything is installed:
```zsh
~/Music
➜ python --version
Python 3.8.7

~/Music
❯ youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

~/Music
❯ pip-user install youtube_to_mpd
Requirement already satisfied: youtube_to_mpd in /home/lpanebr/.pyenv/versions/3.8.7/envs/neovim3/lib/python3.8/site-packages (0.1)

~/Music
➜ mpd --version
Music Player Daemon 0.21.20 (0.21.20)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But the command: `python -m youtube_to_mpd -p PLcTnSFPnn_Kkdqsy3YJRLL-59OLwHF0ny` gives me this error:

```
Traceback (most recent call last):
  File "/home/lpanebr/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lpanebr/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lpanebr/.pyenv/versions/neovim3/lib/python3.8/site-packages/youtube_to_mpd/__main__.py", line 8, in <module>
    from main import run
ModuleNotFoundError: No module named 'main'
```
**Any idea?**

**Comment by lorenzovianello-vivaldigroup** [comment]
I'm facing the same issue.
Did you solved something?
